<template>
  <div class="flex flex-col min-h-screen bg-white">
    <Header :changelanguage="changeLanguage" />
    <main class="flex-1">
      <slot />
    </main>
    <Footer />
  </div>
</template>

<script setup>
import { ref, provide } from 'vue'
import Header from '~/components/Header.vue'
import Footer from '~/components/Footer.vue'

const currentLanguage = ref('fr') // Langue par défaut
const translations = {
  fr: {
    //Header
    label: "Langue",
    headerup : "Uploader",
    headernav: "Navigation",
    headerconstraints: "Contraintes",
    //footer
    footerText: '2025 TrashMap. Tous droits réservés.',
    //Index
    slogan: "Aidez votre ville à rester propre. Uploadez des images de poubelles et contribuez à une meilleure gestion des déchets urbains grâce à l’IA.",
    uploadButton: 'Uploader une image',
    dashboardprev: 'Dashboard',
    dashboardDescription: 'Retrouvez ici les graphiques, les cartes interactives et les statistiques en temps réel.',
    // Realtimeindicators
    realtimetitle: "Indicateurs en temps réel",
    loc:"Localisation",
    pop:"Population",
    day: "Jour",
    meteo: "Météo",
    gettime: "Date d’acquisition",
    hab:"hab",
    //DashboardPreview
    filtre : "Filtres",
    allStates: "Tous",
    emptyState: "Vide",
    overflowState: "Débordée",
    allPeriods: "Toutes périodes",
    last7Days: "7 derniers jours",
    last30Days: "30 derniers jours",
    thisYear: "Cette année",
    loaddash: "Chargement des données du dashboard...",
    visu1title: "Nombre total d’images",
    visu2title: "Répartition des annotations",
    visu3title: "Couleur Moyenne globale",
    visu4title: "Histogramme global des tailles (px)",
    nbimg : "Nombre d'images",
    visu5title: "Histogramme des tons dominants",
    Red:"Rouge",
    Green:"Vert",
    Blue:"Bleu",
    visu6title: "Histogramme des contrastes",
    low: "Faible < 30",
    medium: "30 < Moyen < 60",
    high: "60 < Élevé",
    desccont: "Faible #contraste < 30, Moyen 30 < #contraste < 60, et Élevé #contraste > 60.",
    visu7title: "Histogramme du nombre de contours",
    visu8title: "Contours moyen selon les labels",
    nbmoycontours: "Nombre moyen de contours",
    emptyLabel: "Vide",
    fullLabel: "Pleine",
    noLabel: "Sans label",
    visu9title: "Tons dominants par label",
    visu10title: "Niveau de contraste par label",
    annotationsLabel: "Annotations",
    cartetitle : "Carte des marchés, chantiers, poubelles et zones à risques",
    checkboxmarche : "Marchés actifs aujourd'hui",
    checkboxchantiers : "Chantiers en cours",
    checkboxdepots : "Poubelles",
    checkboxzones : "Zones à risques",
    dashboardDescription : "Visualisations interactives et statistiques en temps réel",
    //Carte Dashboard
    end: "Fin : ",
    depID: "Dépôt ID :",
    seeimg : "Voir l'image",
    //Upload
    drag:"Déposez votre image ici",
    upload:"Uploader une image",
    fromat : "Formats : ",
    img:"Image",
    instruc:"Cliquez pour choisir un fichier à uploader",
    selc:"Sélectionnez l'état de la poubelle",
    lieu:"Entrez un lieu (ex: Paris)",
    env:"Envoyer",
    safe:"Image et annotation enregistrée dans la base de données !!!",
    modano:"Modifier l'annotation",
    err1 : "Format non supporté. JPG/JPEG/PNG/WEBP requis.",
    err2 : "Fichier trop volumineux. 5 Mo max.",
    err3 : "Image trop petite. Minimum 500×500 px.",
    err4 : "Lieu introuvable",
    err5 : "Veuillez remplir tous les champs.",
    err6 : "Upload réussi",
    //Navigation
    navtitle: "Navigation des images",
    navtips:"Utilisez les flèches ou raccourcis clavier pour parcourir les images.",
    prec:"Précédente",
    suiv:"Suivante",
    imginfo: "Informations de l'image :",
    métadata: "Métadonnées",
    date: "Date",
    size: "Taille",
    dim: "Dimensions",
    contrast: "Contraste",
    edges: "Contours",
    lum: "Luminance",
    annotation: "Annotation",
    annoter: "Annoter",
    lat: "Latitude",
    lon: "Longitude",
    statut: "Statut",
    val:"Valider",
    pietitle:"Composition RGB (Moyenne)",
    moyrgb: "Moyenne",
    historgb: "Histogramme RGB",
    histolum: "Histogramme de luminance",
    noimg:"Aucune image à afficher.",
    //Contraintes
    constraintsTitle: "Configuration des contraintes",
    constraintsDescription: "Paramétrez les règles de classification et activez le mode intelligent.",
    modeint:"Mode intelligent activé",
    modeman:"Mode manuel activé",
    save:"Enregistrer",
  },
  en: {
    //Header
    label: "Language",
    headerup: "Upload",
    headernav: "Navigation",
    headerconstraints: "Constraints",
    uploadButton: 'Upload an image',
    //Footer
    footerText: '2025 TrashMap. All rights reserved.',
    //Index
    slogan: "Help your city stay clean. Upload images of trash and contribute to better urban waste management with AI.",
    dashboardprev: 'Dashboard Overview',
    dashboardDescription: 'Soon, graphs, interactive maps, and collection statistics will be displayed here.',
    // Realtimeindicators
    realtimetitle: "Real-time indicators",
    loc: "Location",
    pop:"Population",
    day: "Day",
    meteo: "Weather",
    gettime: "Acquisition date",
    hab: "inhab",
    //DashboardPreview
    filtre : "Filters",
    allStates: "All",
    emptyState: "Empty",
    overflowState: "Overflowing",
    allPeriods: "All periods",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    thisYear: "This year",
    loaddash: "Loading dashboard data...",
    visu1title: "Total number of images",
    visu2title: "Distribution of annotations",
    visu3title: "Average global color",
    visu4title: "Global size histogram (px)",
    nbimg : "Number of images",
    visu5title: "Histogram of dominant tones",
    Red: "Red",
    Green: "Green",
    Blue: "Blue",
    visu6title: "Histogram of contrasts",
    low: "Low < 30",
    medium: "30 < Mid < 60",
    high: "60 < High",
    desccont: "Low #contrast < 30, Medium 30 < #contrast < 60, and High #contrast > 60.",
    visu7title: "Histogram of number of edges",
    visu8title: "Average number of edges by labels",
    nbmoycontours: "Average number of edges",
    emptyLabel: "Empty",
    fullLabel: "Full",
    noLabel: "No label",
    visu9title: "Dominant Tones by label",
    visu10title: "Contrast level by label",
    annotationsLabel: "Annotations",
    cartetitle : "Map of markets, construction sites, trash bins, and risk zones",
    checkboxmarche : "Markets active today",
    checkboxchantiers : "Construction sites",
    checkboxdepots : "Trash bins",
    checkboxzones : "Risk zones",
    dashboardDescription : "Interactive visualizations and real-time statistics",
    //Carte Dashboard
    end: "End : ",
    depID: "Bin ID :",
    seeimg: "View image",
    //Upload
    drag: "Drop your image here",
    upload: "Upload an image",
    fromat: "Formats: ",
    img: "Image",
    instruc: "Click to choose a file to upload",
    selc: "Select the state of the trash bin",
    lieu: "Enter a location (e.g., Paris)",
    env: "Send",
    safe: "Image and annotation saved in the database !!!",
    modano: "Modify annotation",
    err1: "Unsupported format. JPG/JPEG/PNG/WEBP required.",
    err2: "File too large. Max 5 MB.",
    err3: "Image too small. Minimum 500×500 px.",
    err4: "Location not found",
    err5: "Please fill in all fields.",
    err6: "Upload successful",
    //Navigation
    navtitle: "Image Navigation",
    navtips: "Use the arrows or keyboard shortcuts to navigate through the images.",
    prec: "Previous",
    suiv: "Next",
    imginfo: "Image Information :",
    métadata: "Metadata",
    date: "Date",
    size: "Size",
    dim: "Dimensions",
    contrast: "Contrast",
    edges: "Edges",
    lum: "Luminance",
    annotation: "Annotation",
    annoter: "Annotate",
    lat: "Latitude",
    lon: "Longitude",
    statut: "Status",
    val: "Validate",
    pietitle: "RGB Composition (Average)",
    moyrgb: "Average",
    historgb: "RGB Histogram",
    histolum: "Luminance Histogram",
    noimg: "No image to display.",
    //Contraintes
    constraintsTitle: "Constraints Configuration",
    constraintsDescription: "Set classification rules and enable intelligent mode.",
    modeint: "Intelligent mode enabled",
    modeman: "Manual mode enabled",
    save: "Save",
  },
  ar: {
    //Header
    label: "اللغة",
    headerup: "تحميل",
    headernav: "التنقل",
    headerconstraints: "القيود",
    //Footer
    footerText: "2025 TrashMap. جميع الحقوق محفوظة.",
    //Index
    slogan: "ساعد مدينتك على البقاء نظيفة. قم بتحميل صور الحاويات وساهم في تحسين إدارة النفايات باستخدام الذكاء الاصطناعي.",
    uploadButton: "تحميل صورة",
    dashboardprev: "لوحة البيانات",
    dashboardDescription: "الرسوم البيانية، الخرائط التفاعلية، والإحصائيات في الوقت الحقيقي.",
    // Realtimeindicators
    realtimetitle: "مؤشرات في الوقت الحقيقي",
    loc: "الموقع",
    pop: "عدد السكان",
    day: "اليوم",
    meteo: "الطقس",
    gettime: "تاريخ الالتقاط",
    hab: "نسمة",
    //DashboardPreview
    filtre: "فلاتر",
    allStates: "الكل",
    emptyState: "فارغة",
    overflowState: "ممتلئة جدًا",
    allPeriods: "كل الفترات",
    last7Days: "آخر 7 أيام",
    last30Days: "آخر 30 يومًا",
    thisYear: "هذه السنة",
    loaddash: "جاري تحميل بيانات لوحة التحكم...",
    visu1title: "إجمالي عدد الصور",
    visu2title: "توزيع التعليقات",
    visu3title: "متوسط اللون العام",
    visu4title: "الرسم البياني العام للأحجام (px)",
    nbimg: "عدد الصور",
    visu5title: "الرسم البياني للألوان السائدة",
    Red: "أحمر",
    Green: "أخضر",
    Blue: "أزرق",
    visu6title: "الرسم البياني للتباين",
    low: "منخفض < 30",
    medium: "30 < متوسط < 60",
    high: "مرتفع > 60",
    desccont: "منخفض < 30، متوسط بين 30 و 60، مرتفع > 60.",
    visu7title: "الرسم البياني لعدد الحواف",
    visu8title: "متوسط عدد الحواف حسب التصنيفات",
    nbmoycontours: "متوسط عدد الحواف",
    emptyLabel: "فارغة",
    fullLabel: "ممتلئة",
    noLabel: "بدون تصنيف",
    visu9title: "الألوان السائدة حسب التصنيف",
    visu10title: "مستوى التباين حسب التصنيف",
    annotationsLabel: "التعليقات",
    cartetitle: "خريطة الأسواق، المشاريع، الحاويات، والمناطق الخطرة",
    checkboxmarche: "الأسواق النشطة اليوم",
    checkboxchantiers: "المشاريع الجارية",
    checkboxdepots: "الحاويات",
    checkboxzones: "المناطق الخطرة",
    //Carte Dashboard
    end: "النهاية: ",
    depID: "معرّف الحاوية:",
    seeimg: "عرض الصورة",
    //Upload
    drag: "أسقط صورتك هنا",
    upload: "تحميل صورة",
    fromat: "الصيغ: ",
    img: "صورة",
    instruc: "انقر لاختيار ملف للتحميل",
    selc: "اختر حالة الحاوية",
    lieu: "أدخل موقعًا (مثال: باريس)",
    env: "إرسال",
    safe: "تم حفظ الصورة والتعليق في قاعدة البيانات!",
    modano: "تعديل التعليق",
    err1: "صيغة غير مدعومة. الصيغ المقبولة: JPG/JPEG/PNG/WEBP.",
    err2: "الملف كبير جدًا. الحد الأقصى 5 ميغابايت.",
    err3: "الصورة صغيرة جدًا. الحد الأدنى 500×500 بكسل.",
    err4: "الموقع غير موجود",
    err5: "يرجى ملء جميع الحقول.",
    err6: "تم التحميل بنجاح",
    //Navigation
    navtitle: "تصفح الصور",
    navtips: "استخدم الأسهم أو اختصارات لوحة المفاتيح للتنقل بين الصور.",
    prec: "السابق",
    suiv: "التالي",
    imginfo: "معلومات الصورة:",
    métadata: "البيانات الوصفية",
    date: "التاريخ",
    size: "الحجم",
    dim: "الأبعاد",
    contrast: "التباين",
    edges: "الحواف",
    lum: "السطوع",
    annotation: "التعليق",
    annoter: "علق",
    lat: "خط العرض",
    lon: "خط الطول",
    statut: "الحالة",
    val: "تأكيد",
    pietitle: "تركيب ألوان RGB (المتوسط)",
    moyrgb: "المتوسط",
    historgb: "رسم بياني لألوان RGB",
    histolum: "رسم بياني للسطوع",
    noimg: "لا توجد صورة لعرضها.",
    //Contraintes
    constraintsTitle: "إعداد القيود",
    constraintsDescription: "اضبط قواعد التصنيف وفعّل الوضع الذكي.",
    modeint: "تم تفعيل الوضع الذكي",
    modeman: "تم تفعيل الوضع اليدوي",
    save: "حفظ",
  }
}

// Fournir les données aux composants enfants
provide('currentLanguage', currentLanguage)
provide('translations', translations)
</script>